import Head from "next/head";
import { getSession, signOut } from "next-auth/react";
import { MedicineDetailsTable } from "../src/components/MedicineDetailsTable";
import axios from "axios";

const dashboard = ({ medicines }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <MedicineDetailsTable medicines={medicines} />
      </main>
    </div>
  );
};

export default dashboard;

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/signin",
        permanent: false,
      },
    };
  }

  const { data: medicines } = await axios.get(
    `${process.env.HOST_URL}/api/medicine?userId=${session.userId}`
  );

  return {
    props: {
      session,
      medicines,
    },
  };
};
